version: '3.8'
services:
  app:
    image: openjdk:8-jdk-alpine
    container_name: springboot-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musteri
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=2023
    volumes:
      - ./target:/app
    ports:
      - "2023:2023"
    command: ["java", "-jar", "/app/akilli-ik-1.0.jar"]
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: musteri
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
